# Hisilicon Hi35xx sample Makefile.param
export PARAM_FILE := ../../../Makefile.param
include $(PARAM_FILE)

COMMON_DIR:=$(PWD)/../../common
AUDIO_ADP_DIR:=$(PWD)/../../audio/adp
include ../../Makefile.param


MPI_LIBS += $(REL_LIB)/libnnie.a

CFLAGS += -I$(PWD)/../common

ifeq ($(ARM_ARCH), amp)
CFLAGS += -DAMP
else
CFLAGS += -DSMP
endif

